import type { Theme } from "./types";
import colors from "../colors";
import fonts from "../fonts";
import sizes from "../sizes";

export const defaultTheme: Theme = {
  base: {
    color: {
      collection: {
        "deep-blue": colors.deepBlue,
        "galaxy-purple": colors.galaxyPurple,
        green: colors.green,
        red: colors.red,
        yellow: colors.yellow,
        slate: colors.slate,
        grey: colors.grey,
        pink: colors.pink,
      },
      foundations: {
        black: colors.black,
        white: colors.white,
      },
    },
    font: {
      family: fonts.family,
      height: fonts.height,
      spacing: fonts.spacing,
      paragraphSpacing: fonts.paragraphSpacing,
      size: fonts.size,
      weight: fonts.weight,
    },
    size: {
      dimension: sizes.dimensions,
    },
  },
  color: {
    primary: "deep-blue",
    secondary: "galaxy-purple",
    accent: "pink",
    error: "red",
    information: "deep-blue",
    success: "green",
    warning: "yellow",
    "neutral-dark": "slate",
    "neutral-light": "grey",
  },
  font: {
    family: {
      body: "content",
      bodyShort: "content",
      bodyLong: "content",
      label: "content",
      labelLong: "content",
      h1: "headline",
      h2: "headline",
      h3: "headline",
      h4: "headline",
      h5: "headline",
      h6: "headline",
      hyperlink: "content",
      hyperlinkHover: "content",
      caption: "content",
    },
    spacing: {
      hyperlink: "base",
      hyperlinkHover: "base",
      body: "base",
      bodyShort: "md",
      bodyLong: "base",
      label: "md",
      labelLong: "md",
      h1: "xs",
      h2: "xs",
      h3: "xs",
      h4: "xs",
      h5: "xs",
      h6: "xs",
      caption: "xs",
    },
    height: {
      hyperlink: "xs",
      hyperlinkHover: "xs",
      bodyShort: "xs",
      body: "sm",
      bodyLong: "base",
      label: "sm",
      labelLong: "base",
      h1: "4xl",
      h2: "3xl",
      h3: "2xl",
      h4: "xl",
      h5: "lg",
      h6: "md",
      caption: "xs",
    },
    size: {
      hyperlink: "base",
      hyperlinkHover: "base",
      bodyShort: "base",
      body: "sm",
      bodyLong: "base",
      label: "base",
      labelLong: "base",
      h1: "4xl",
      h2: "3xl",
      h3: "2xl",
      h4: "xl",
      h5: "lg",
      h6: "md",
      caption: "xs",
    },
    weight: {
      hyperlink: "regular",
      hyperlinkHover: "regular",
      bodyShort: "regular",
      body: "regular",
      bodyLong: "regular",
      label: "regular",
      labelLong: "regular",
      h1: "bold",
      h2: "bold",
      h3: "semiBold",
      h4: "semiBold",
      h5: "semiBold",
      h6: "semiBold",
      caption: "medium",
    },
    paragraphSpacing: {
      hyperlink: "base",
      hyperlinkHover: "base",
      bodyShort: "base",
      body: "base",
      bodyLong: "base",
      label: "base",
      labelLong: "base",
      h1: "base",
      h2: "base",
      h3: "base",
      h4: "base",
      h5: "base",
      h6: "base",
      caption: "base",
    },
  },
  size: {
    border: {
      width: {
        xs: 25,
        sm: 50,
        md: 100,
      },
      radius: {
        none: 0,
        "3xs": 50,
        "2xs": 100,
        xs: 150,
        sm: 200,
        md: 300,
        lg: 400,
        xl: 500,
        "2xl": 600,
        "3xl": 700,
        "4xl": 800,
        pill: 1900,
      },
    },
    spacing: {
      "4xs": 50,
      "3xs": 100,
      "2xs": 200,
      xs: 300,
      sm: 400,
      md: 500,
      lg: 600,
      xl: 800,
      "2xl": 1000,
      "3xl": 1100,
      "4xl": 1300,
    },
  },
  palette: {
    dark: {
      surface: {
        primary: {
          default: { color: "neutral-light", scale: 100 },
          defaultHover: { color: "neutral-light", scale: 300 },
          defaultSubtle: { color: "neutral-light", scale: 900 },
          defaultSubtleHover: { color: "neutral-light", scale: 800 },
          defaultSubtleHoverAlt: { color: "neutral-light", scale: 900 },
        },
        secondary: {
          default: { color: "neutral-dark", scale: 1000 },
          defaultHover: { color: "neutral-dark", scale: 900 },
          defaultSubtle: { color: "neutral-dark", scale: 1000 },
          defaultSubtleHover: { color: "neutral-dark", scale: 1000 },
        },
        disabled: {
          default: { color: "neutral-dark", scale: 1100 },
        },
        error: {
          default: { color: "error", scale: 300 },
          defaultHover: { color: "error", scale: 400 },
          defaultSubtle: { color: "error", scale: 900 },
          defaultSubtleHover: { color: "error", scale: 1000 },
        },
        success: {
          default: { color: "success", scale: 400 },
          defaultHover: { color: "success", scale: 500 },
          defaultSubtle: { color: "success", scale: 900 },
          defaultSubtleHover: { color: "success", scale: 1000 },
        },
        information: {
          default: { color: "information", scale: 300 },
          defaultHover: { color: "information", scale: 400 },
          defaultSubtle: { color: "information", scale: 900 },
          defaultSubtleHover: { color: "information", scale: 1000 },
        },
        warning: {
          default: { color: "warning", scale: 400 },
          defaultHover: { color: "warning", scale: 500 },
          defaultSubtle: { color: "warning", scale: 900 },
          defaultSubtleHover: { color: "warning", scale: 1000 },
        },
        default: {
          default: { color: "neutral-dark", scale: 1100 },
        },
        page: {
          default: { color: "neutral-dark", scale: 1100 },
        },
        pageAlternative: {
          default: { color: "neutral-dark", scale: 1100 },
        },
        alternative: {
          default: { color: "neutral-dark", scale: 1100 },
        },
      },
      text: {
        primary: {
          onColor: { color: "primary", scale: 1000 },
          onColorHover: { color: "primary", scale: 1000 },
          onColorSubtle: { color: "primary", scale: 200 },
          onColorSubtleHover: { color: "primary", scale: 300 },
          default: { color: "primary", scale: 200 },
          defaultHover: { color: "primary", scale: 300 },
        },
        secondary: {
          onColor: { color: "secondary", scale: 1000 },
          onColorHover: { color: "secondary", scale: 1000 },
          onColorSubtle: { color: "secondary", scale: 200 },
          onColorSubtleHover: { color: "secondary", scale: 300 },
          default: { color: "secondary", scale: 200 },
          defaultHover: { color: "secondary", scale: 300 },
        },
        disabled: {
          default: { color: "neutral-light", scale: 300 },
          onColor: { color: "neutral-light", scale: 300 },
        },
        error: {
          onColor: { color: "neutral-light", scale: 900 },
          onColorHover: { color: "neutral-light", scale: 1100 },
          onColorSubtle: { color: "error", scale: 300 },
          onColorSubtleHover: { color: "error", scale: 400 },
          default: { color: "error", scale: 300 },
          defaultHover: { color: "error", scale: 400 },
        },
        success: {
          onColor: { color: "neutral-light", scale: 900 },
          onColorHover: { color: "neutral-light", scale: 1100 },
          onColorSubtle: { color: "success", scale: 300 },
          onColorSubtleHover: { color: "success", scale: 400 },
          default: { color: "success", scale: 300 },
          defaultHover: { color: "success", scale: 400 },
        },
        information: {
          onColor: { color: "neutral-light", scale: 900 },
          onColorHover: { color: "neutral-light", scale: 1100 },
          onColorSubtle: { color: "information", scale: 300 },
          onColorSubtleHover: { color: "information", scale: 400 },
          default: { color: "information", scale: 300 },
          defaultHover: { color: "information", scale: 400 },
        },
        warning: {
          onColor: { color: "neutral-light", scale: 900 },
          onColorHover: { color: "neutral-light", scale: 1100 },
          onColorSubtle: { color: "warning", scale: 300 },
          onColorSubtleHover: { color: "warning", scale: 400 },
          default: { color: "warning", scale: 300 },
          defaultHover: { color: "warning", scale: 400 },
        },
        default: {
          body: { color: "neutral-light", scale: 100 },
          hero: { color: "neutral-light", scale: 200 },
          heading: { color: "neutral-light", scale: 200 },
          caption: { color: "neutral-light", scale: 300 },
          placeholder: { color: "neutral-light", scale: 300 },
        },
        onColor: {
          hero: { color: "neutral-light", scale: 1100 },
          heading: { color: "neutral-light", scale: 1100 },
          body: { color: "neutral-light", scale: 1000 },
          caption: { color: "neutral-light", scale: 800 },
          placeholder: { color: "neutral-light", scale: 700 },
        },
        accent: {
          default: { color: "accent", scale: 300 },
          defaultHover: { color: "accent", scale: 400 },
          onColor: { color: "neutral-light", scale: 900 },
          onColorHover: { color: "neutral-light", scale: 1100 },
          onColorSubtle: { color: "accent", scale: 300 },
          onColorSubtleHover: { color: "accent", scale: 400 },
        },
      },
      icon: {
        primary: {
          onColor: { color: "primary", scale: 900 },
          onColorHover: { color: "primary", scale: 1000 },
          onColorSubtle: { color: "primary", scale: 200 },
          onColorSubtleHover: { color: "primary", scale: 300 },
          default: { color: "primary", scale: 400 },
          defaultHover: { color: "primary", scale: 500 },
          defaultSubtle: { color: "primary", scale: 400 },
          defaultSubtleHover: { color: "primary", scale: 500 },
        },
        secondary: {
          onColor: { color: "secondary", scale: 300 },
          onColorHover: { color: "secondary", scale: 400 },
          onColorSubtle: { color: "secondary", scale: 300 },
          onColorSubtleHover: { color: "secondary", scale: 400 },
          default: { color: "secondary", scale: 300 },
          defaultHover: { color: "secondary", scale: 400 },
        },
        disabled: {
          default: { color: "neutral-light", scale: 300 },
          onColor: { color: "neutral-light", scale: 300 },
        },
        error: {
          onColor: { color: "neutral-light", scale: 1000 },
          onColorHover: { color: "neutral-light", scale: 800 },
          onColorSubtle: { color: "error", scale: 300 },
          onColorSubtleHover: { color: "error", scale: 400 },
          default: { color: "error", scale: 300 },
          defaultHover: { color: "error", scale: 400 },
        },
        success: {
          onColor: { color: "neutral-light", scale: 900 },
          onColorHover: { color: "neutral-light", scale: 800 },
          onColorSubtle: { color: "success", scale: 400 },
          onColorSubtleHover: { color: "success", scale: 300 },
          default: { color: "success", scale: 400 },
          defaultHover: { color: "success", scale: 500 },
        },
        information: {
          onColor: { color: "neutral-light", scale: 900 },
          onColorHover: { color: "neutral-light", scale: 1000 },
          onColorSubtle: { color: "information", scale: 400 },
          onColorSubtleHover: { color: "information", scale: 500 },
          default: { color: "information", scale: 400 },
          defaultHover: { color: "information", scale: 500 },
        },
        warning: {
          onColor: { color: "neutral-light", scale: 900 },
          onColorHover: { color: "neutral-light", scale: 1000 },
          onColorSubtle: { color: "warning", scale: 400 },
          onColorSubtleHover: { color: "warning", scale: 500 },
          default: { color: "warning", scale: 400 },
          defaultHover: { color: "warning", scale: 500 },
        },
      },
      border: {
        primary: {
          default: { color: "primary", scale: 300 },
          defaultHover: { color: "primary", scale: 400 },
          defaultSubtle: { color: "primary", scale: 700 },
          defaultSubtleHover: { color: "primary", scale: 800 },
          focus: { color: "primary", scale: 300 },
        },
        error: {
          default: { color: "error", scale: 300 },
          defaultHover: { color: "error", scale: 400 },
          defaultSubtle: { color: "error", scale: 800 },
          defaultSubtleHover: { color: "error", scale: 900 },
          focus: { color: "error", scale: 300 },
        },
        success: {
          default: { color: "success", scale: 400 },
          defaultHover: { color: "success", scale: 500 },
          defaultSubtle: { color: "success", scale: 900 },
          defaultSubtleHover: { color: "success", scale: 1000 },
          focus: { color: "success", scale: 400 },
        },
        information: {
          default: { color: "information", scale: 400 },
          defaultHover: { color: "information", scale: 500 },
          defaultSubtle: { color: "information", scale: 900 },
          defaultSubtleHover: { color: "information", scale: 1000 },
          focus: { color: "information", scale: 400 },
        },
        warning: {
          default: { color: "warning", scale: 400 },
          defaultHover: { color: "warning", scale: 500 },
          defaultSubtle: { color: "warning", scale: 900 },
          defaultSubtleHover: { color: "warning", scale: 1000 },
          focus: { color: "warning", scale: 400 },
        },
        secondary: {
          default: { color: "secondary", scale: 800 },
          defaultHover: { color: "secondary", scale: 700 },
          defaultSubtle: { color: "secondary", scale: 800 },
          defaultSubtleHover: { color: "secondary", scale: 700 },
          focus: { color: "secondary", scale: 800 },
        },
        disabled: {
          default: { color: "neutral-light", scale: 1000 },
          onColor: { color: "neutral-light", scale: 200 },
        },
        default: {
          default: { color: "neutral-light", scale: 800 },
          onColor: { color: "neutral-light", scale: 800 },
        },
      },
    },
    light: {
      surface: {
        primary: {
          default: { color: "primary", scale: 700 },
          defaultHover: { color: "primary", scale: 800 },
          defaultSubtle: { color: "primary", scale: 100 },
          defaultSubtleHover: { color: "primary", scale: 150 },
          defaultSubtleHoverAlt: { color: "primary", scale: 150 },
        },
        secondary: {
          default: { color: "secondary", scale: 800 },
          defaultHover: { color: "secondary", scale: 900 },
          defaultSubtle: { color: "secondary", scale: 100 },
          defaultSubtleHover: { color: "secondary", scale: 150 },
        },
        disabled: {
          default: { color: "neutral-dark", scale: 100 },
        },
        error: {
          default: { color: "error", scale: 800 },
          defaultHover: { color: "error", scale: 900 },
          defaultSubtle: { color: "error", scale: 100 },
          defaultSubtleHover: { color: "error", scale: 150 },
        },
        success: {
          default: { color: "success", scale: 800 },
          defaultHover: { color: "success", scale: 900 },
          defaultSubtle: { color: "success", scale: 100 },
          defaultSubtleHover: { color: "success", scale: 150 },
        },
        information: {
          default: { color: "information", scale: 800 },
          defaultHover: { color: "information", scale: 900 },
          defaultSubtle: { color: "information", scale: 100 },
          defaultSubtleHover: { color: "information", scale: 150 },
        },
        warning: {
          default: { color: "warning", scale: 800 },
          defaultHover: { color: "warning", scale: 900 },
          defaultSubtle: { color: "warning", scale: 100 },
          defaultSubtleHover: { color: "warning", scale: 150 },
        },
        default: {
          default: { color: "foundation.white" },
        },
        page: {
          default: { color: "foundation.white" },
        },
        pageAlternative: {
          default: { color: "neutral-light", scale: 100 },
        },
        alternative: {
          default: { color: "neutral-light", scale: 100 },
        },
      },
      text: {
        primary: {
          onColor: { color: "primary", scale: 100 },
          onColorHover: { color: "primary", scale: 200 },
          onColorSubtle: { color: "primary", scale: 900 },
          onColorSubtleHover: { color: "primary", scale: 1000 },
          default: { color: "primary", scale: 800 },
          defaultHover: { color: "primary", scale: 900 },
        },
        secondary: {
          onColor: { color: "secondary", scale: 100 },
          onColorHover: { color: "secondary", scale: 200 },
          onColorSubtle: { color: "secondary", scale: 900 },
          onColorSubtleHover: { color: "secondary", scale: 1000 },
          default: { color: "secondary", scale: 800 },
          defaultHover: { color: "secondary", scale: 900 },
        },
        disabled: {
          default: { color: "neutral-light", scale: 600 },
          onColor: { color: "neutral-light", scale: 600 },
        },
        error: {
          onColor: { color: "neutral-light", scale: 100 },
          onColorHover: { color: "neutral-light", scale: 200 },
          onColorSubtle: { color: "error", scale: 700 },
          onColorSubtleHover: { color: "error", scale: 800 },
          default: { color: "error", scale: 800 },
          defaultHover: { color: "error", scale: 900 },
        },
        success: {
          onColor: { color: "neutral-light", scale: 100 },
          onColorHover: { color: "neutral-light", scale: 200 },
          onColorSubtle: { color: "success", scale: 800 },
          onColorSubtleHover: { color: "success", scale: 900 },
          default: { color: "success", scale: 800 },
          defaultHover: { color: "success", scale: 900 },
        },
        information: {
          onColor: { color: "neutral-light", scale: 100 },
          onColorHover: { color: "neutral-light", scale: 200 },
          onColorSubtle: { color: "information", scale: 800 },
          onColorSubtleHover: { color: "information", scale: 900 },
          default: { color: "information", scale: 800 },
          defaultHover: { color: "information", scale: 900 },
        },
        warning: {
          onColor: { color: "neutral-light", scale: 100 },
          onColorHover: { color: "neutral-light", scale: 200 },
          onColorSubtle: { color: "warning", scale: 800 },
          onColorSubtleHover: { color: "warning", scale: 900 },
          default: { color: "warning", scale: 800 },
          defaultHover: { color: "warning", scale: 900 },
        },
        default: {
          body: { color: "neutral-light", scale: 900 },
          hero: { color: "neutral-light", scale: 1100 },
          heading: { color: "neutral-light", scale: 1100 },
          caption: { color: "neutral-light", scale: 700 },
          placeholder: { color: "neutral-light", scale: 700 },
        },
        onColor: {
          hero: { color: "neutral-light", scale: 100 },
          heading: { color: "neutral-light", scale: 100 },
          body: { color: "neutral-light", scale: 100 },
          caption: { color: "neutral-light", scale: 200 },
          placeholder: { color: "neutral-light", scale: 300 },
        },
        accent: {
          default: { color: "accent", scale: 800 },
          defaultHover: { color: "accent", scale: 900 },
          onColor: { color: "neutral-light", scale: 100 },
          onColorHover: { color: "neutral-light", scale: 200 },
          onColorSubtle: { color: "accent", scale: 800 },
          onColorSubtleHover: { color: "accent", scale: 900 },
        },
      },
      icon: {
        primary: {
          onColor: { color: "primary", scale: 100 },
          onColorHover: { color: "primary", scale: 200 },
          onColorSubtle: { color: "primary", scale: 900 },
          onColorSubtleHover: { color: "primary", scale: 1000 },
          default: { color: "primary", scale: 800 },
          defaultHover: { color: "primary", scale: 900 },
          defaultSubtle: { color: "primary", scale: 500 },
          defaultSubtleHover: { color: "primary", scale: 600 },
        },
        secondary: {
          onColor: { color: "secondary", scale: 800 },
          onColorHover: { color: "secondary", scale: 900 },
          onColorSubtle: { color: "secondary", scale: 800 },
          onColorSubtleHover: { color: "secondary", scale: 900 },
          default: { color: "secondary", scale: 800 },
          defaultHover: { color: "secondary", scale: 900 },
        },
        disabled: {
          default: { color: "neutral-light", scale: 600 },
          onColor: { color: "neutral-light", scale: 600 },
        },
        error: {
          onColor: { color: "neutral-light", scale: 100 },
          onColorHover: { color: "neutral-light", scale: 200 },
          onColorSubtle: { color: "error", scale: 700 },
          onColorSubtleHover: { color: "error", scale: 800 },
          default: { color: "error", scale: 800 },
          defaultHover: { color: "error", scale: 900 },
        },
        success: {
          onColor: { color: "neutral-light", scale: 100 },
          onColorHover: { color: "neutral-light", scale: 200 },
          onColorSubtle: { color: "success", scale: 800 },
          onColorSubtleHover: { color: "success", scale: 900 },
          default: { color: "success", scale: 800 },
          defaultHover: { color: "success", scale: 900 },
        },
        information: {
          onColor: { color: "neutral-light", scale: 100 },
          onColorHover: { color: "neutral-light", scale: 200 },
          onColorSubtle: { color: "information", scale: 800 },
          onColorSubtleHover: { color: "information", scale: 900 },
          default: { color: "information", scale: 800 },
          defaultHover: { color: "information", scale: 900 },
        },
        warning: {
          onColor: { color: "neutral-light", scale: 100 },
          onColorHover: { color: "neutral-light", scale: 200 },
          onColorSubtle: { color: "warning", scale: 800 },
          onColorSubtleHover: { color: "warning", scale: 900 },
          default: { color: "warning", scale: 800 },
          defaultHover: { color: "warning", scale: 900 },
        },
      },
      border: {
        primary: {
          default: { color: "primary", scale: 800 },
          defaultHover: { color: "primary", scale: 900 },
          defaultSubtle: { color: "primary", scale: 300 },
          defaultSubtleHover: { color: "primary", scale: 500 },
          focus: { color: "primary", scale: 900 },
        },
        error: {
          default: { color: "error", scale: 800 },
          defaultHover: { color: "error", scale: 900 },
          defaultSubtle: { color: "error", scale: 150 },
          defaultSubtleHover: { color: "error", scale: 300 },
          focus: { color: "error", scale: 800 },
        },
        success: {
          default: { color: "success", scale: 800 },
          defaultHover: { color: "success", scale: 900 },
          defaultSubtle: { color: "success", scale: 150 },
          defaultSubtleHover: { color: "success", scale: 300 },
          focus: { color: "success", scale: 800 },
        },
        information: {
          default: { color: "information", scale: 800 },
          defaultHover: { color: "information", scale: 900 },
          defaultSubtle: { color: "information", scale: 150 },
          defaultSubtleHover: { color: "information", scale: 300 },
          focus: { color: "information", scale: 800 },
        },
        warning: {
          default: { color: "warning", scale: 800 },
          defaultHover: { color: "warning", scale: 900 },
          defaultSubtle: { color: "warning", scale: 150 },
          defaultSubtleHover: { color: "warning", scale: 300 },
          focus: { color: "warning", scale: 800 },
        },
        secondary: {
          default: { color: "secondary", scale: 800 },
          defaultHover: { color: "secondary", scale: 900 },
          defaultSubtle: { color: "secondary", scale: 300 },
          defaultSubtleHover: { color: "secondary", scale: 500 },
          focus: { color: "secondary", scale: 900 },
        },
        disabled: {
          default: { color: "neutral-light", scale: 200 },
          onColor: { color: "neutral-light", scale: 900 },
        },
        default: {
          default: { color: "neutral-light", scale: 300 },
          onColor: { color: "foundation.white" },
        },
      },
    },
  },
};
